from tkinter import *
from tkinter import messagebox
from tkinter import font
from PIL import ImageTk, Image

# This part would contain Customer FirstName, LastName, UserName, Password, and Email.
# FirstName would be generated by the system
# Details should be saved to a DB.

# Define the user signup class which handles the GUI for the user signup
class UserSignup:
    def __init__(self, window):
        self.window = window
        self.window.geometry('1024x768')
        self.window.state('zoomed')
        self.window.resizable(0, 0)
        self.window.configure(bg='#ffffff')  # Set window background to white

        # Create a frame for the signup section
        self.signup_frame = Frame(self.window, width=1200, height=500, bg='#f0f0f0')
        self.signup_frame.place(relx=0.5, rely=0.5, anchor=CENTER)  # Center the frame

        # Text
        self.txt = 'Signup'
        signup_font = font.Font(family="Georgia", size=40, weight="bold")
        self.heading = Label(self.signup_frame, text=self.txt, font=signup_font, fg='#000000', bg='#f0f0f0')
        self.heading.place(x=300, y=20, width=200, height=40)

        # Logo
        self.side_logo = Image.open('Image/AshlingBankSmall.png')
        photo = ImageTk.PhotoImage(self.side_logo)
        self.side_logo_label = Label(self.signup_frame, image=photo, bg='#f0f0f0')  # Background matches frame
        self.side_logo_label.image = photo  # Keep a reference to avoid garbage collection
        self.side_logo_label.place(x=20, y=80)  # Adjust logo position to fit in the frame

if __name__ == "__main__":
    window = Tk()
    UserSignup(window)
    window.title("Ashling-Create Account")
    window.mainloop()
